services:
  - type: web
    name: emotion-diary
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn emotion_diary.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emotion-diary-db
          property: connectionString
      - key: MYAPP_AES_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: emotion-diary-db
